name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      env:
        CI: true  # Set CI environment variable
      run: |
        python src/train.py 2>&1 | grep -v "Downloading\|Extracting"
        
    - name: Run tests
      run: |
        pytest tests/ -v --no-header --no-summary