name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p data
        mkdir -p models
        mkdir -p visualizations
        
    - name: Train model
      env:
        CI: true
      run: |
        echo "=== Starting Model Training ==="
        python src/train.py 2>&1 | tee training.log || (cat training.log && exit 1)
        echo "=== Training Complete ==="
        
    - name: Run tests
      run: |
        echo "=== Starting Tests ==="
        pytest tests/ -v
        echo "=== Testing Complete ==="
        
    - name: Upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: training-artifacts
        path: |
          models/
          training.log