name: ML Pipeline

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Train model
      env:
        CI: true
      run: |
        echo "=== Starting Model Training ==="
        python src/train.py | grep -E "Parameters|Progress|Accuracy|Loss|Model saved"
        echo "=== Training Complete ==="
        
    - name: Run tests
      run: |
        echo "=== Starting Tests ==="
        pytest tests/ -v
        echo "=== Testing Complete ==="